### ISSUE TITLE
Featureunlock suggestions 

### ISSUE THREAD

**Issue by THEALIFHAKER1** [aidanbae123/ThinkPad-E14-Hackintosh-gen-4-AMD#2]
Did you try feature unlock by acidanthera to address all continuity feature?

**Comment by aidanbae123** [comment]
FeatureUnlock enables continuity features on INTEL machines.
![Screenshot 2024-02-13 at 14 31 33](https://github.com/aidanbae123/ThinkPad-E14-Hackintosh-gen-4-AMD/assets/146204079/0cca39b6-2970-443d-ae26-2917fdee4ff8)

**Comment by THEALIFHAKER1** [comment]
How about other than sidecar?

**Comment by aidanbae123** [comment]
Any wireless continuity features need a natively supported card. This build uses an intel card with airportitwlm, which has no support for these features. A little bit of research would have told you this.

**Comment by aidanbae123** [comment]
The only feature that sort of works wirelessly is handoff. Via a wired connection, continuity camera and hotspot are functional.

**Comment by THEALIFHAKER1** [comment]
Ah i see sorry then as i new to hackintosh (just dip 4 day ago) thx for providing info

**Comment by aidanbae123** [comment]
Ah no worries. Lmk if you have any more questions
